from UnsortedPriorityQueue import UnsortedPriorityQueue

pd = UnsortedPriorityQueue()

pd.add(1, 'A')
pd.add(2, 'B')
pd.add(3, 'C')
pd.add(4, 'D')
pd.add(5, 'F')
pd.add(6, 'G')
print("COLA DE PRIORIDAD:")
print(pd)
print()
print("VACIO? ")
print(pd.is_empty())
print()
print("MINIMO")
print(pd.min())
print(pd)
print()
print("REMOVER MINIMO")
pd.remove_min()
print(pd)
